# Generated by Django 2.2.5 on 2019-10-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('is_active', models.PositiveSmallIntegerField(choices=[(0, '未激活'), (1, '已激活')], default=0)),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('info', models.CharField(blank=True, max_length=256, null=True)),
                ('avatar', models.CharField(blank=True, max_length=512, null=True)),
                ('bg_pic', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_create', models.DateTimeField(auto_now_add=True)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, '拼车'), (2, '短途出游'), (3, '长途旅行'), (4, '组队练习'), (5, '其他出行')])),
                ('location', models.CharField(max_length=128)),
                ('member_count', models.PositiveSmallIntegerField()),
                ('mobile', models.CharField(max_length=128)),
                ('info', models.CharField(max_length=512)),
                ('pictures', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='main.User')),
                ('participants', models.ManyToManyField(related_name='participants', to='main.User')),
            ],
        ),
    ]
